/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Stat = IDL.Record({
  'id' : IDL.Nat,
  'value' : IDL.Nat,
  'name' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'createStat' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'deleteStat' : IDL.Func([IDL.Nat], [], []),
  'getStats' : IDL.Func([], [IDL.Vec(Stat)], ['query']),
  'getStatsSortedByTimestamp' : IDL.Func([], [IDL.Vec(Stat)], ['query']),
  'updateStat' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Stat = IDL.Record({
    'id' : IDL.Nat,
    'value' : IDL.Nat,
    'name' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'createStat' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'deleteStat' : IDL.Func([IDL.Nat], [], []),
    'getStats' : IDL.Func([], [IDL.Vec(Stat)], ['query']),
    'getStatsSortedByTimestamp' : IDL.Func([], [IDL.Vec(Stat)], ['query']),
    'updateStat' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };